### ISSUE TITLE
[v10.2.10] Unable to trigger autocomplete due to #442

### ISSUE THREAD

**Issue by QuentiumYT** [TarekRaafat/autoComplete.js#492]
- [ ] **System Information**
  - [ ] Browser type and version: Brave
  - [ ] OS type and version: Linux Mint 22.3
  - [ ] WINDOWS: be sure to indicate which terminal you're using -- (i.e., cmd.exe, powershell, git- bash, cygwin, Ubuntu via windows subsystem for linux, etc...): gnome terminal
  - [ ] Node version (IF applicable): NA
    - [ ] Any error messages that may be in the console where you ran npm start: None
  - [ ] Any error messages in the JS console: Uncaught (in promise) TypeError: i.src(...).then is not a function

- [ ] **Describe the bug**
Regression caused by #442, when I rollback to 10.2.9 it works like before. It might be interesting to dig again into it :/

- [ ] **To Reproduce**
```js
new autoComplete({
        selector: '#site-search',
        placeHolder: 'Rechercher un site',
        diacritics: true,
        data: {
          src: () =>
            newSites.map((site) => ({
              label: site.label_site,
              value: site.id_site,
            })),
          keys: ['label'],
        },
```

- [ ] **Expected behavior**
It should work like before

- [ ] **Screenshots or GIF's (optional, but HIGHLY RECOMMENDED)**
Every time I type in the input, this error is triggered:
```js
Uncaught (in promise) TypeError: i.src(...).then is not a function
    at autoComplete.min.js:1:3273
    at new Promise (<anonymous>)
    at autoComplete.min.js:1:3206
    at new Promise (<anonymous>)
    at d (autoComplete.min.js:1:3137)
    at autoComplete.min.js:1:5851
    at new Promise (<anonymous>)
    at k (autoComplete.min.js:1:5620)
    at e (autoComplete.min.js:1:6547)
    at autoComplete.min.js:1:6625```

**Comment by TarekRaafat** [comment]
Hello @QuentiumYT,

Thanks a lot for the detailed report and for tracking this down to #442, that level of detail is incredibly helpful and much appreciated!

I confirmed the regression. Here is the full picture:

PR #442 (`v10.2.10`) replaced the previous `AsyncFunction` constructor check with an unconditional `await data.src(query)`. Native JavaScript handles `await` on a non-Promise value correctly, however the legacy `rollup-plugin-nodent` used in the build pipeline lowers `await x` into a direct `x.then(...)` call, which throws when `x` is a plain array returned by a synchronous `data.src`. That is exactly what your config triggers.

So the chain is:
1. `v10.2.9` and earlier worked via the explicit `AsyncFunction` check
2. `v10.2.10` removed that check (correct fix for swc/transpiler false-negatives), but exposed `nodent`'s broken `await` lowering on sync return values
3. Result: `i.src(...).then is not a function` on every keystroke for sync array sources

Two actions on the way:
- A targeted fix will land in `v10.3.0` (currently in progress) by wrapping the call so a thenable is always returned, restoring full compatibility with synchronous `data.src` while keeping the swc/transpiler fix from #442 intact
- The root cause, the unmaintained `nodent` plugin, is already on the roadmap for removal in `v10.4.0` as part of the broader build modernization

In the meantime, pinning to `v10.2.9` is a valid workaround as you found, or if you prefer staying on `v10.2.10`, wrapping your `src` to return a Promise also works:
```js
src: () => Promise.resolve(newSites.map((site) => ({ ... })))
```

I will post here again as soon as `v10.3.0` is published. Tracking this directly under #492.

Thanks again for the great catch and for taking the time to report it so precisely, much appreciated!

Have a nice day, cheers! :)

**Comment by QuentiumYT** [comment]
You're welcome :) Thanks for your quick reply as well!

Glad 10.3.0 is in the pipe 🌟 

Have a nice day :)

**Comment by QuentiumYT** [comment]
Hello, can you release a fix @TarekRaafat before 10.3.0 maybe? Thanks

**Comment by QuentiumYT** [comment]
Please could you release a fix @TarekRaafat? It's annoying when I bump the dependencies. Thanks
