### ISSUE TITLE
Mozilla compatibility error

### ISSUE THREAD

**Issue by ghost** [TarekRaafat/autoComplete.js#27]
Hi there,

I'm using autoComplete on multiple website, I just saw than it's not working on Mozilla Firefox (65.0.1)
It gave me this error : `TypeError: t.filter is not a function       - autoComplete.min.js:1:2962`

On Chrome everythings is ok. Any idea ? 
Thanks for this awesome js librairie !

**Comment by TarekRaafat** [comment]
Hello @F-Locos,

Thanks for reporting that error. Currently I don't know what could be the reason behind it.

Initially I don't think that it's because of the 'filter' function, I believe that it's supported already in Firefox v65 but I will look into it and get back to you as soon as I find a fix for it.

Cheers! :)

**Comment by TarekRaafat** [comment]
@F-Locos, I've tested `autoComplete.js` on Firefox starting version 60 up to 65, and unfortunately couldn't reproduce the error, it worked perfectly fine with no errors.

I would appreciate if you could provide more details on the error you're getting to help me identify the root cause.

Thank you! :)

**Comment by F-Locos** [comment]
The only thing which can help you it's my json file used by your plugin and my website.
I've sent to u an email about it.
Thanks to you !

**Comment by F-Locos** [comment]
It's looks like to be a bad chars interpretation. 
- For one of my website, it's now works for Firefox
- For an other one, it's still bugued
If I found exactly what, I'll tell you!

**Comment by TarekRaafat** [comment]
Hello @F-Locos,

Are you still having the same issue?

**Comment by F-Locos** [comment]
> Hello @F-Locos,
> 
> Are you still having the same issue?

Sorry,
I did not have enough time to check that, I'll do it soon as possible.

**Comment by TarekRaafat** [comment]
@F-Locos thank you, much appreciated. :)

**Comment by F-Locos** [comment]
> Hello @F-Locos,
> 
> Are you still having the same issue?

Yes, I still have, even after updated my project with the latest version of your product.
Looks to still be the same error. So not fixed 
![image](https://user-images.githubusercontent.com/7100248/62944856-daee8e80-bddd-11e9-9a52-b37d2940bc3b.png)

**Comment by F-Locos** [comment]
Hmm, my generated json is now working with your example. It looks like to be script side. I'm searching for more information.

**Comment by F-Locos** [comment]
The error on firefox is fired at the line 242 from the 'data' object var where his type is 'Promise'.
![image](https://user-images.githubusercontent.com/7100248/62945993-1b4f0c00-bde0-11e9-8a97-2238e6e5d3df.png)

**Comment by F-Locos** [comment]
@TarekRaafat I finally found it. I'm using Sylius, and the app resource js make your script broken. 
You should maybe try to install the skeleton of sylius and keep the default theme to reproduce that bug.
